name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  tag-image:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v1
        with:
          commit: "${{ github.event.workflow_run.head_sha }}"
          prefix: "sha-"
