name: Deploy Website

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  tag-image:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v1
        with:
          commit: "${{ github.event.workflow_run.head_sha }}"
          prefix: "sha-"
      - uses: docker/setup-buildx-action@v1
      - name: Build image for commit
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.commit.outputs.short }}
